# Refer to utils/config.py for definition and options.
version = "EyelashNet"
dist = false

[model]
batch_size = 4
imagenet_pretrain = true
imagenet_pretrain_path = "/home/xqj/zhangzr/GCA-Matting-master/pretrain/model_best_resnet34_En_nomixup.pth"
    [model.arch]
    encoder = "resnet_gca_encoder_29"
    decoder = "res_gca_decoder_22"

[train]
total_step = 200000
warmup_step = 5000
val_step = 2000
clip_grad = true
G_lr = 4e-4
# Uncomment to resume training
#resume_checkpoint = "latest_model"
#reset_lr = false

[data]
train_fg = "/home/xqj/zhangzr/GCA-Matting-master/data/EyelashNet/train/image"
train_alpha = "/home/xqj/zhangzr/GCA-Matting-master/data/EyelashNet/train/mask"
train_bg = "/home/xqj/zhangzr/GCA-Matting-master/data/coco_bg"
pupil_bg = "/home/xqj/zhangzr/GCA-Matting-master/data/pupil_bg"
test_merged = "/home/xqj/zhangzr/GCA-Matting-master/data/BaselineTestDataset/image"
test_alpha = "/home/xqj/zhangzr/GCA-Matting-master/data/BaselineTestDataset/mask"
test_trimap = "/home/xqj/zhangzr/GCA-Matting-master/data/BaselineTestDataset/trimap"
workers = 2
augmentation = true

[log]
tensorboard_step = 100
tensorboard_image_step = 2000
logging_step =  1
logging_level = "INFO"
checkpoint_step = 2000

[test]
merged = "/home/xqj/zhangzr/GCA-Matting-master/data/BaselineTestDataset/image"
alpha = "/home/xqj/zhangzr/GCA-Matting-master/data/BaselineTestDataset/mask"
trimap = "/home/xqj/zhangzr/GCA-Matting-master/data/BaselineTestDataset/trimap"
scale = "origin"
checkpoint = "best_model"
fast_eval = true
# Uncomment to save predicted alpha
alpha_path = "prediction"
